//
//  LandingRouter.swift
//  CleanArchitecture
//
//  Created by Marcos Molero on 23/6/18.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol MonumentListRoutingLogic {
    func routeToMonumentDetail()
}

protocol MonumentListDataPassing {
    func passDataToNextScene(for segue:UIStoryboardSegue)
    var dataStore: MonumentListDataStore? { get }
}

class MonumentListRouter: MonumentListRoutingLogic, MonumentListDataPassing {
    
    weak var viewController: MonumentListViewController?
    var dataStore: MonumentListDataStore?
    
    struct SegueIdentifiers {
        static let monumentDetail = "showDetail"
    }
    // MARK: Navigation
    func routeToMonumentDetail() {
        viewController?.performSegue(withIdentifier: SegueIdentifiers.monumentDetail, sender: nil)
    }
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
