//
//  LandingPresenter.swift
//  CleanArchitecture
//
//  Created by Marcos Molero on 23/6/18.
//  Copyright (c) 2018 Marcos Molero. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol MonumentListPresentationLogic {
    func presentGetListSuccess(response: MonumentListScene.getList.Response)
    func presentGetListError(response: MonumentListScene.getList.Response)
}

class MonumentListPresenter: MonumentListPresentationLogic {
    
    weak var viewController: MonumentListDisplayLogic?
    
    // MARK: Presentation logic
    func presentGetListSuccess(response: MonumentListScene.getList.Response) {
        let viewModel = MonumentListScene.getList.ViewModel(displayListMonumentView: mapListView(list: response.listMonument), displayError: "")
        viewController?.displayGetListSuccess(viewModel: viewModel)
    }
    
    func presentGetListError(response: MonumentListScene.getList.Response) {
        let viewModel = mapMonumentListErrorToViewModelError(response: response)
        viewController?.displayGetListError(viewModel: viewModel)
    }
    
    func mapMonumentListErrorToViewModelError(response: MonumentListScene.getList.Response) -> MonumentListScene.getList.ViewModel {
        return MonumentListScene.getList.ViewModel(displayListMonumentView: mapListView(list: response.listMonument), displayError: "")
    }
}
